import Head from 'next/head';
import { useRouter } from 'next/router';

import styles from '../styles/Home.module.css'
import Header from '../components/header';
import SideMenu from '../components/side-menu';
import SignIn from '../components/sign-in';

const Layout = ({ children, title = 'Novel Comic Web' }) => {
  const router = useRouter();
  const pathname = router.pathname;

  return (
    <div className={styles.container}>
      <Head>
        <title>{ title }</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <body>
        <Header/>
        <SideMenu/>
        <SignIn/>

        <main className={styles.main}>
          { children }
        </main>
      </body>

      <footer className={styles.footer}>
        Copyright 2021 - tinhto
      </footer>
    </div>
  )
}

export default Layout;