import Layout from '../layouts/Main';
import ProductList from '../components/product-list';

export default function Home() {
  return (
    <Layout>
      <ProductList/>
    </Layout>
    // <div className={styles.container}>
    //   <Head>
    //     <title>Novel comic web</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    //   <main className={styles.main}>
    //     <Header/>

    //     <SideMenu/>

    //     <ProductList />

    //     <SignIn/>
    //   </main>

    //   <footer className={styles.footer}>
    //     Copyright 2021 - tinhto
    //   </footer>
    // </div>
  )
}